version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - music-service
      - recommendation-service
    networks:
      - beatly-network

  user-service:
    build: ./user-service
    container_name: user-service
    expose:
      - "3001"
    networks:
      - beatly-network

  music-service:
    build: ./music-service
    container_name: music-service
    expose:
      - "3002"
    networks:
      - beatly-network

  recommendation-service:
    build: ./recommendation-service
    container_name: recommendation-service
    expose:
      - "3003"
    networks:
      - beatly-network

networks:
  beatly-network:
    driver: bridge
